export const TIER_CONFIGS = {
  landing: {
    id: 'landing',
    name: 'Landing',
    slug: 'landing',
    eyebrow: '// SINGLE-PAGE FOCUS',
    price: 1990,
    priceLabel: '€1,990',
    timeline: '3 days',
    timelineRange: 'Day 0 — 3',
    accent: 'accent',
    accentVar: 'var(--accent)',
    heroTagline: 'One Page. One Promise.',
    heroSubline:
      'A single, scroll-stopping landing page that converts. Hero, features, pricing, contact — sculpted in our cinematic stack and shipped in three days.',
    heroDecorWord: 'Pixel-perfect.',
    heroBlurb: 'Most teams over-build. The smartest founders ship one page that closes. We build that page.',
    bestFor: [
      'Solo founders launching a product',
      'Coaches & consultants with a single offer',
      'Newsletter creators capturing emails',
      'Pre-launch waitlists for SaaS',
    ],
    deepFeatures: [
      { icon: 'Spark', title: 'Cinematic Hero', body: 'Full-bleed, motion-driven hero with the kind of opening shot that makes scrollers stop. GSAP scroll-tied animation. Custom typography pairing.' },
      { icon: 'Layout', title: '4 Strategic Sections', body: 'Hero → Features → Social Proof → CTA. Every section earns its place. No filler. No fluff. Mobile-first.' },
      { icon: 'Type', title: 'Conversion Copy Frame', body: 'We hand you a tested copy structure. You fill in the specifics, we polish. Or upgrade to full copywriting.' },
      { icon: 'Stripe', title: '1 Form / 1 Integration', body: 'Email capture, Stripe payment, Cal.com booking — pick one. Wired to your tool of choice.' },
      { icon: 'Speed', title: '95+ Lighthouse', body: 'Sub-1s load. Optimized images, fonts, JS. Vercel/Cloudflare edge. SEO-ready out of the box.' },
      { icon: 'Mobile', title: 'Mobile-First', body: 'Designed for thumbs. Tested on iPhone, Android, iPad. The motion adapts to small screens — never breaks.' },
    ],
    notIncluded: [
      "Multi-page navigation (that's the Business tier)",
      'Blog / CMS (that\'s Business)',
      "E-commerce (that's Store)",
      "User accounts (that's Web App)",
    ],
    timelineSteps: [
      { n: '01', title: 'Discovery', range: 'Day 0', body: '30-min call. We map your offer, your customer, the one action you want them to take.' },
      { n: '02', title: 'Figma Prototype', range: 'Day 1—2', body: 'You receive a clickable Figma. One revision round. We do not build until you sign off.' },
      { n: '03', title: 'Build & Motion', range: 'Day 3—5', body: 'Cinematic build. Daily Loom updates. Preview link by Day 4.' },
      { n: '04', title: 'Launch', range: 'Day 6—7', body: 'Deploy to your domain. Full ownership transfer. SEO + analytics live.' },
    ],
    addonRecommendations: ['copywriting', 'motion', 'seo'],
    faq: [
      { q: 'Can I add more pages later?', a: 'Yes — landing pages are designed to scale into the Business tier. We keep your design system intact, you only pay the difference.' },
      { q: "What if I don't have copy yet?", a: 'You have three options: write it yourself with our tested structure, upgrade to full copywriting (€690), or use our AI copy assist included in Motion Package.' },
      { q: 'Will it work on Webflow / Framer?', a: 'No. We build in our cinematic stack — Next.js, GSAP, Framer Motion, Tailwind. You own the source. Hosting on Cloudflare Pages by default.' },
      { q: 'Do you guarantee conversion?', a: 'No-one can. But we do guarantee a 95+ Lighthouse score, a sub-1s load, and a 3-day delivery. The conversion is on the offer — we make sure the page does its job.' },
      { q: "What's the 7-day deposit policy?", a: "You get 7 days from deposit to back out for any reason. Full refund. After that, we've started work — deposit is committed to your project." },
    ],
    examples: [
      { name: 'KNZN.de', url: 'knzn.de', role: 'Solo automotive launch', stat: '14k visits / 4 weeks' },
      { name: 'BodyAI', url: 'bodyai.de', role: 'Wellness app waitlist', stat: '2.1k emails captured' },
      { name: 'Stub Build', url: '#', role: 'Coach launch page', stat: '47% scroll-to-CTA' },
    ],
    proofStat: { number: '7', unit: 'DAYS', label: 'AVG. DELIVERY' },
  },

  business: {
    id: 'business',
    name: 'Business',
    slug: 'business',
    eyebrow: '// MULTI-PAGE WEBSITE',
    price: 3990,
    priceLabel: '€3,990',
    timeline: '14 days',
    timelineRange: 'Day 0 — 14',
    accent: 'accent',
    accentVar: 'var(--accent)',
    heroTagline: 'A Hub. Not a Brochure.',
    heroSubline:
      'A 5–7 page company website that builds trust at scale. About, Services, Portfolio, Blog, Contact — orchestrated under one cinematic system.',
    heroDecorWord: 'Cohesive.',
    heroBlurb:
      'When the offer is layered, you need pages that work together. We design the system before we design the pages.',
    bestFor: [
      'Service businesses (agencies, studios, clinics)',
      'Local businesses with a regional reach',
      'B2B companies with multiple services',
      'Established brands needing a refresh',
    ],
    deepFeatures: [
      { icon: 'Layout', title: '5–7 Pages, One System', body: 'Home, About, Services, Portfolio, Blog, Contact, Legal. Built on a shared design system — change one token, everything updates.' },
      { icon: 'Type', title: 'Content Architecture', body: 'Sitemap, navigation hierarchy, copy structure. We design the information architecture before any pixel.' },
      { icon: 'Cms', title: 'Sanity CMS Integration', body: 'Edit copy, images, blog posts without code. Built-in preview. Versioning. Multi-user access.' },
      { icon: 'Blog', title: 'Blog Engine', body: 'MDX-powered blog with reading time, table of contents, social cards, RSS, and SEO-perfect schema.' },
      { icon: 'Multi', title: 'DE + EN Bilingual', body: 'Native German + English routing. Hreflang tags. Localized OG cards. Switch language without losing context.' },
      { icon: 'Forms', title: 'Smart Contact Forms', body: 'Multi-step contact form with CRM integration. Spam-proof. Email + Slack notifications. GDPR consent.' },
      { icon: 'Search', title: 'SEO Foundation', body: 'Sitemap, robots.txt, schema markup, meta optimization, GA4 + Search Console. First 5 keywords ranked.' },
      { icon: 'Speed', title: 'Edge-Cached Performance', body: 'Cloudflare edge for sub-1s loads worldwide. ISR for blog. Image optimization. 95+ Lighthouse on every page.' },
    ],
    notIncluded: [
      "E-commerce checkout (that's Store)",
      "User accounts / login (that's Web App)",
      "Custom backend logic (that's Web App)",
    ],
    timelineSteps: [
      { n: '01', title: 'Discovery', range: 'Day 0—1', body: '90-min strategy call. Sitemap workshop. Brand audit. Competitive review.' },
      { n: '02', title: 'Architecture', range: 'Day 2—3', body: 'Wireframes for every page. Information hierarchy. Navigation logic. You sign off.' },
      { n: '03', title: 'Visual Design', range: 'Day 4—6', body: 'Figma high-fidelity for hero pages. Design system tokenized. One revision round.' },
      { n: '04', title: 'Build & CMS', range: 'Day 7—12', body: 'All pages built. CMS configured. Content migrated. Daily Loom updates.' },
      { n: '05', title: 'QA & Launch', range: 'Day 13—14', body: 'Cross-browser QA. Speed audit. Deploy. Domain transfer. Analytics live.' },
    ],
    addonRecommendations: ['copywriting', 'motion', 'seo', 'maintenance'],
    faq: [
      { q: 'How many pages exactly?', a: 'Up to 7 standard pages. Need more? €290/extra. Most clients ship with 5–7.' },
      { q: 'Can my team edit the site after launch?', a: 'Yes — Sanity CMS comes with full team access. We do a 60-min training call before handoff. Edit copy, swap images, post to the blog.' },
      { q: 'What if my brand needs a refresh?', a: 'We can refresh logo, type, colors as part of the build (no extra cost). A full rebrand is a separate engagement — we partner with select brand studios for that.' },
      { q: 'Do you write the copy?', a: 'Optional add-on (€690). Or we polish your draft. Or we hand you a tested structure. Your call.' },
      { q: 'What about hosting & maintenance?', a: 'Cloudflare Pages hosting included. Maintenance retainer is optional (€290/mo, first month free) — security patches, content updates, monthly analytics review.' },
    ],
    examples: [
      { name: 'Aurion Peptides', url: 'aurionpeptides.com', role: 'Bilingual lab supplier', stat: '8 pages / DE+EN' },
      { name: 'Studio Lumen', url: 'studiolumen.de', role: 'Architecture practice', stat: '+340% time on site' },
      { name: 'Helios Clinic', url: '#', role: 'Medical clinic refresh', stat: '95+ Lighthouse' },
    ],
    proofStat: { number: '14', unit: 'DAYS', label: 'AVG. DELIVERY' },
  },

  store: {
    id: 'store',
    name: 'Store',
    slug: 'store',
    eyebrow: '// E-COMMERCE WITH STRIPE',
    price: 6990,
    priceLabel: '€6,990',
    timeline: '21 days',
    timelineRange: 'Day 0 — 21',
    accent: 'accent-2',
    accentVar: 'var(--accent-2)',
    heroTagline: 'A Storefront That Sells.',
    heroSubline:
      'A complete e-commerce build with Stripe checkout, Supabase customer accounts, and the cinematic motion that makes carts feel inevitable.',
    heroDecorWord: 'Inevitable.',
    heroBlurb:
      'The Shopify look is dead. The brands winning in 2026 sell from sites that feel like films. We build those.',
    badge: 'MOST POPULAR',
    bestFor: [
      'Premium DTC brands (apparel, supplements, home)',
      'Independent product makers',
      'Digital product creators (templates, courses)',
      'Brands shipping under 50 SKUs',
    ],
    deepFeatures: [
      { icon: 'Cart', title: 'Stripe Checkout', body: 'Full Stripe integration. Apple Pay, Google Pay, Klarna, SEPA. Automatic tax calculation (EU + US). Subscriptions optional.' },
      { icon: 'Db', title: 'Supabase Customer DB', body: 'Customer accounts. Order history. Address book. Magic-link auth. Email confirmations. RLS-secured.' },
      { icon: 'Catalog', title: 'Product Catalog (≤50)', body: 'Categories, variants (size/color/material), inventory tracking, product imagery, video. Search + filters.' },
      { icon: 'Cms', title: 'Sanity CMS', body: 'Edit products, copy, blog without code. Bulk import via CSV. Inventory dashboard.' },
      { icon: 'Email', title: 'Email Automation', body: 'Order confirmations. Shipping updates. Abandoned cart (3-touch sequence). Welcome flow. Resend or Postmark.' },
      { icon: 'Cookie', title: 'GDPR Cookie Banner', body: 'Compliant consent management. Granular cookie control. EU + UK ready. Auto-detect locale.' },
      { icon: 'Shipping', title: 'Shipping Logic', body: 'Flat rate, tiered, free-over-X. Multi-zone (DE / EU / Global). Customs declaration ready. Sendcloud / DHL integration optional.' },
      { icon: 'Speed', title: 'Edge-Cached Catalog', body: 'Sub-1s product page loads. ISR caching. Image optimization. PPR for cart. 95+ Lighthouse.' },
    ],
    notIncluded: [
      'Custom checkout flow beyond Stripe (custom build)',
      'Subscription billing logic (Custom tier)',
      'Multi-vendor marketplace (Web App / Custom)',
    ],
    timelineSteps: [
      { n: '01', title: 'Discovery', range: 'Day 0—2', body: 'Catalog audit. Pricing strategy. Shipping zones. Tax setup. Stripe account configuration.' },
      { n: '02', title: 'Architecture', range: 'Day 3—4', body: 'Product taxonomy. Variants schema. Customer flow. Cart UX. Checkout logic.' },
      { n: '03', title: 'Visual Design', range: 'Day 5—9', body: 'Storefront, product page, cart, checkout, account. Motion direction. One revision round.' },
      { n: '04', title: 'Build & Stripe', range: 'Day 10—17', body: 'Full build. Stripe integration. Supabase auth. Product import. Email flows. Daily Loom.' },
      { n: '05', title: 'QA & Launch', range: 'Day 18—21', body: 'Test transactions in Stripe sandbox. EU tax verification. Live deploy. Domain transfer.' },
    ],
    addonRecommendations: ['copywriting', 'motion', 'seo', 'maintenance'],
    faq: [
      { q: 'Can I sell more than 50 products?', a: 'Yes — €1,990 add-on covers up to 200 SKUs with bulk import workflow. Beyond 200, we move to the Custom tier.' },
      { q: 'What about Shopify migration?', a: 'We migrate from Shopify. Products, customers, orders. Data migration is a €490 add-on — usually 2–3 days extra.' },
      { q: 'Do you handle PCI compliance?', a: 'Stripe handles all PCI. Card data never touches your server. You stay PCI-DSS compliant by design.' },
      { q: 'Can I add subscriptions?', a: 'Stripe subscriptions are a €390 add-on — recurring billing, customer portal, cancel/upgrade flows.' },
      { q: 'What about wholesale / B2B pricing?', a: 'Custom pricing tiers via customer groups is a €490 add-on. Or we move to the Web App tier for full B2B portal.' },
      { q: 'Refunds & returns?', a: 'Stripe refunds via dashboard. Returns workflow (RMA, label generation) is a €290 add-on with Sendcloud integration.' },
    ],
    examples: [
      { name: 'Aurion Peptides Shop', url: 'aurionpeptides.com', role: 'Premium peptide store', stat: '€32k MRR' },
      { name: 'Indigo Atelier', url: '#', role: 'Independent fashion', stat: '4.2% conv. rate' },
      { name: 'Noquito', url: 'noquito.com', role: 'Coffee subscription', stat: '140 paid subs' },
    ],
    proofStat: { number: '21', unit: 'DAYS', label: 'AVG. DELIVERY' },
  },

  webapp: {
    id: 'webapp',
    name: 'Web App',
    slug: 'webapp',
    eyebrow: '// CUSTOM APPLICATION',
    price: 12990,
    priceLabel: '€12,990+',
    timeline: '4–6 weeks',
    timelineRange: 'Day 0 — 35',
    accent: 'accent',
    accentVar: 'var(--accent)',
    heroTagline: 'A Tool That Earns Its Daily Open.',
    heroSubline:
      'A custom web application — full auth, dashboards, billing, admin. Built to be opened every day, not abandoned in three weeks.',
    heroDecorWord: 'Indispensable.',
    heroBlurb:
      'Most "MVPs" are templates with hope. We build the actual product. With the actual stack. With the actual quality bar.',
    bestFor: [
      'Indie founders with a validated SaaS idea',
      'Internal tools for medium-sized companies',
      'B2B portals and customer dashboards',
      'AI wrapper products (Claude / OpenAI / Anthropic)',
    ],
    deepFeatures: [
      { icon: 'Auth', title: 'Full Authentication', body: 'Email + password, magic link, Google OAuth, GitHub OAuth. Forgot password. Email verification. Session management. RLS-secured.' },
      { icon: 'Dashboard', title: 'Custom Dashboards', body: 'User dashboard, admin dashboard, analytics views. Charts, tables, filters. Real-time updates via Supabase Realtime.' },
      { icon: 'Billing', title: 'Stripe Subscription', body: 'Plans, trials, upgrades, downgrades, cancellation. Customer portal. Invoice generation. Webhooks. EU VAT MOSS.' },
      { icon: 'Admin', title: 'Admin Panel', body: 'User management, content moderation, analytics, billing overview, support tools. Role-based access control.' },
      { icon: 'Db', title: 'Postgres Schema', body: 'Production-ready Supabase schema. Migrations. Triggers. Indexes. Row-level security on everything.' },
      { icon: 'Api', title: 'API Layer', body: 'Type-safe API (tRPC or REST). Rate limiting. Request validation. Error handling. OpenAPI docs.' },
      { icon: 'Email', title: 'Transactional Email', body: 'Welcome, password reset, billing receipts, notifications. Resend or Postmark. Templated. Internationalized.' },
      { icon: 'Ai', title: 'AI Integration', body: 'Claude / OpenAI / Anthropic SDK setup. Streaming responses. Token usage tracking. Optional vector search (pgvector).' },
      { icon: 'N8n', title: 'n8n Workflow Hooks', body: 'Webhook endpoints for n8n automations. Customer signup → Slack. Failed payment → Email. Custom triggers.' },
      { icon: 'Speed', title: 'Performance Engineering', body: 'PPR, ISR, edge runtime where appropriate. Skeleton loading. Optimistic UI. <100ms p50 API.' },
    ],
    notIncluded: [
      'Mobile native apps (we build PWA — works installed)',
      'Desktop apps (we build web — works everywhere)',
      'Custom AI model training (consult separately)',
    ],
    timelineSteps: [
      { n: '01', title: 'Discovery', range: 'Week 1', body: '2x 90-min calls. PRD writing. User stories. Schema design. Tech stack lock.' },
      { n: '02', title: 'Architecture', range: 'Week 1—2', body: 'Database schema. API contracts. Auth flows. Billing model. State diagrams.' },
      { n: '03', title: 'Design', range: 'Week 2', body: 'Figma for every screen. Design system. Empty states. Error states. Two revision rounds.' },
      { n: '04', title: 'Core Build', range: 'Week 3—4', body: 'Auth, database, core features. Daily preview deploys. Loom updates 3x/week.' },
      { n: '05', title: 'Polish & QA', range: 'Week 5', body: 'Edge cases. Cross-browser. Mobile. Accessibility. Performance audit.' },
      { n: '06', title: 'Launch & Handoff', range: 'Week 6', body: 'Production deploy. Monitoring (Sentry, PostHog). Documentation. 60-min walkthrough.' },
    ],
    addonRecommendations: ['copywriting', 'motion', 'maintenance'],
    faq: [
      { q: 'Why €12,990 base instead of fixed?', a: 'Web apps scale by feature surface. Base covers a typical SaaS scope (auth + 1 core feature + billing + admin). We scope additional features in 50% deposits per increment.' },
      { q: "Can I see a real product you've built?", a: 'Yes — BodyAI (wellness AI), Aurion Studio (lab inventory tool), and 2 NDA-protected internal tools for DACH brands. Demo links on request.' },
      { q: 'What stack exactly?', a: 'Next.js 15, TypeScript, Tailwind, Supabase (Postgres + Auth + Storage), Stripe, Resend, Vercel/Cloudflare. tRPC for API. shadcn/ui for components.' },
      { q: 'What if scope creeps mid-build?', a: 'Out-of-scope work gets a separate quote. We do not invisibly bill — every change order is signed before any minute is logged.' },
      { q: 'How do I get the source code?', a: 'GitHub repo transferred on launch. You own everything. No vendor lock-in. We can stay on retainer or you can take it to your own team.' },
      { q: 'What about ongoing maintenance?', a: 'Maintenance retainer (€490/mo) covers security patches, dependency updates, monthly performance review. Feature work is separate engagements.' },
    ],
    examples: [
      { name: 'BodyAI', url: 'bodyai.de', role: 'Wellness AI app', stat: '140 paid users' },
      { name: 'Aurion Studio', url: '#', role: 'Internal lab tool', stat: '12 daily users' },
      { name: 'Stub Engagement', url: '#', role: 'B2B SaaS dashboard', stat: 'NDA — case study soon' },
    ],
    proofStat: { number: '4–6', unit: 'WEEKS', label: 'AVG. DELIVERY' },
  },

  custom: {
    id: 'custom',
    name: 'Custom',
    slug: 'custom',
    eyebrow: '// EVERYTHING ELSE',
    price: 20000,
    priceLabel: '€20,000+',
    timeline: 'Custom',
    timelineRange: 'Custom · scoped per project',
    accent: 'gold',
    accentVar: 'var(--gold)',
    heroTagline: 'When the Brief Breaks the Brackets.',
    heroSubline:
      "Marketplaces. Multi-vendor stores. AI-powered tools. Bespoke flows. When the standard tiers don't fit, we build from a blank page — yours.",
    heroDecorWord: 'Bespoke.',
    heroBlurb:
      'No template. No tier. No assumption. We start with a discovery call, scope the build together, and quote with full transparency.',
    badge: 'BY APPLICATION',
    bestFor: [
      'Multi-vendor marketplaces (Etsy/Substack-class)',
      'AI-native products with novel UX',
      'Internal tools for enterprises',
      'Engagements with custom compliance (HIPAA, SOC2)',
      'Anything not covered by the 4 standard tiers',
    ],
    deepFeatures: [
      { icon: 'Spark', title: 'Discovery Workshop', body: '2-day in-person or 4x 90-min remote. Stakeholder interviews. Strategy doc. PRD. Roadmap. Quote.' },
      { icon: 'Layout', title: 'Bespoke Architecture', body: 'No template. We design the data model, API contracts, auth flows, infrastructure choices to fit YOUR product.' },
      { icon: 'Multi', title: 'Multi-Tenant / Multi-Vendor', body: 'Marketplaces, B2B SaaS, white-label products. Tenant isolation. Per-tenant theming. Custom domain support.' },
      { icon: 'Ai', title: 'Advanced AI Workflows', body: 'Claude/OpenAI integration with RAG, agents, tool use. Vector search. Long-context document analysis. Streaming UI.' },
      { icon: 'Auth', title: 'Enterprise Auth', body: 'SSO (SAML, OIDC). SCIM provisioning. RBAC. Audit logs. Compliance-ready (HIPAA, SOC2 helpers).' },
      { icon: 'Payment', title: 'Custom Billing', body: 'Usage-based pricing, metered billing, tiered plans, marketplace payouts (Stripe Connect), invoice generation, AR workflows.' },
      { icon: 'Db', title: 'Scaled Infrastructure', body: 'Multi-region. Read replicas. Connection pooling. Job queues (BullMQ/Inngest). Background workers. Redis caching.' },
      { icon: 'Speed', title: 'Performance Targets', body: 'p99 latency budgets. Synthetic monitoring. Load testing. Custom CDN config. Edge functions for latency-sensitive paths.' },
    ],
    notIncluded: ["Nothing — if it's buildable on the web, it's in scope. We just scope it together."],
    timelineSteps: [
      { n: '01', title: 'Application', range: 'Day 0', body: "You apply via Cal.com. We review fit within 48h. We don't accept every project — we accept what we can ship at our quality bar." },
      { n: '02', title: 'Discovery', range: 'Week 1—2', body: 'Workshop. Stakeholder interviews. PRD. Architecture doc. Roadmap. Fixed quote.' },
      { n: '03', title: 'Design', range: 'Variable', body: 'Full Figma. Design system. Component library. Stakeholder reviews. Iteration loops.' },
      { n: '04', title: 'Build', range: 'Variable', body: 'Sprint cadence. Weekly demos. Continuous deploys to staging. Integration testing.' },
      { n: '05', title: 'Beta & Polish', range: 'Variable', body: 'Closed beta. Real-user testing. Performance tuning. Edge case hunting.' },
      { n: '06', title: 'Launch', range: 'Variable', body: 'Production deploy. Runbook. Monitoring setup. Team training. Ongoing partnership.' },
    ],
    addonRecommendations: ['copywriting', 'motion', 'maintenance'],
    faq: [
      { q: 'Why does Custom cost €20,000+?', a: "Custom engagements involve a discovery phase (real workshop work, not template clicks), bespoke architecture, and timelines that don't fit pre-priced tiers. Our cheapest Custom-tier engagement to date was €18,000 — most are €30,000–€80,000." },
      { q: 'Can you do a fixed price?', a: 'After discovery (Week 1–2), yes. We give a fixed price for the agreed scope with milestone-based payments. Out-of-scope work is quoted separately and signed before any code.' },
      { q: 'How do you decide what to take on?', a: 'Three filters: (1) Does it match our quality bar? (2) Can we ship it in 8–16 weeks? (3) Does the founder/team have decision authority? If yes, yes, yes — we apply.' },
      { q: 'Can I work with you on a retainer?', a: 'Yes. After launch, retainers are €4,990/mo for ongoing dev (≈40h/mo), or scoped sprints if your needs are uneven.' },
      { q: 'NDA / confidentiality?', a: 'We sign mutual NDAs before discovery. We do not publish client work without written permission. Several of our engagements are NDA-protected — referenced only in private case studies.' },
      { q: 'Equity / partnership deals?', a: 'Rarely. If your product is a fit for our deeper involvement, we discuss SAFE-based partnerships separately. Default is fee-for-service.' },
    ],
    examples: [
      { name: 'NDA Marketplace', url: '#', role: 'Multi-vendor luxury platform', stat: '€140k engagement' },
      { name: 'NDA Internal Tool', url: '#', role: 'Enterprise lab management', stat: '€95k engagement' },
      { name: 'NDA AI Product', url: '#', role: 'AI-native creative tool', stat: '€60k engagement' },
    ],
    proofStat: { number: '∞', unit: 'SCOPE', label: 'BY APPLICATION' },
  },
} as const;

export type TierConfig = (typeof TIER_CONFIGS)[keyof typeof TIER_CONFIGS];
export type TierSlug = keyof typeof TIER_CONFIGS;
