export const BUILDS = [
  {
    id: 'knzn',
    preview: '/portfolio/knzn.jpg',
    available: true,
    title: 'KNZN',
    subtitle: 'License-Plate Commerce',
    label: 'COMMERCE / DÜREN',
    url: 'https://knzn.pages.dev',
    blurb:
      'A full-funnel German Zulassungsdienst commerce site with cinematic GSAP scroll, an embedded AI customer-service agent, and a Lottie stamp ceremony at checkout. €4,200+ first-month revenue.',
    stack: ['Cloudflare', 'Stripe', 'Supabase', 'GSAP', 'Klaus AI'],
    accentVar: 'var(--accent-2)',
    posterGlyph: 'DN-TL · 1984',
    posterMotif: 'plate',
  },
  {
    id: 'aurion',
    preview: '/portfolio/aurion.jpg',
    available: true,
    title: 'Aurion',
    subtitle: 'Peptide Research Platform',
    label: 'E-COMMERCE / LAB',
    url: 'https://aurionlabs.shop',
    blurb:
      'A 39-SKU peptide research storefront with COA transparency on every product, an AI compound-information chatbot, Stripe + Coinbase Commerce checkout, and DHL shipping API integration.',
    stack: ['React 19', 'Vite', 'Supabase', 'Stripe', 'Coinbase', 'DHL'],
    accentVar: 'var(--accent)',
    posterGlyph: 'C₂₀H₃₂N₆O₅',
    posterMotif: 'lab',
  },
  {
    id: 'getautomata',
    preview: '/portfolio/getautomata.jpg',
    available: true,
    title: 'GetAutomata',
    subtitle: 'AI Automation Services',
    label: 'SISTER BRAND / SAAS',
    url: 'https://getautomata.ai',
    blurb:
      'Public-facing marketing landing built on the cinematic stack — converts visitors into automation clients while the dashboard delivers their workflows.',
    stack: ['TypeScript', 'React', 'Workers', 'n8n', 'OpenRouter'],
    accentVar: 'var(--accent)',
    posterGlyph: 'AUTO/MATA · OS',
    posterMotif: 'tron',
  },
  {
    id: 'mission',
    preview: '/portfolio/mission.jpg',
    available: true,
    title: 'Mission Control',
    subtitle: 'GetAutomata Dashboard',
    label: 'DASHBOARD / PRIVATE',
    url: 'https://dashboard.getautomata.ai',
    blurb:
      'The private agent-orchestration dashboard for GetAutomata clients — one design system, two products, end-to-end. Authenticated workflows, real-time runs, billing.',
    stack: ['Supabase', 'Stripe', 'Cloudflare', 'OpenRouter'],
    accentVar: 'var(--gold)',
    posterGlyph: 'GO · MISSION/CTRL',
    posterMotif: 'tron',
  },
  {
    id: 'amboss',
    preview: null,
    available: false,
    title: 'Amboss Apparel',
    subtitle: 'Protective Streetwear',
    label: 'BRAND + STORE / DE',
    url: 'https://ambossapparel.com',
    blurb:
      'A premium brand identity and storefront for an anti-stab protective apparel line — the intersection of fashion and personal safety, designed without compromise on either side.',
    stack: ['Shopify', 'GSAP', '3D Asset Pipeline'],
    accentVar: 'var(--accent-2)',
    posterGlyph: 'AMBOSS · KEVLAR',
    posterMotif: 'apparel',
  },
  {
    id: 'importia',
    preview: '/portfolio/importia.jpg',
    available: true,
    title: 'Importia',
    subtitle: 'Cinematic Visitenkarte',
    label: 'IMPORT BRAND / DE',
    url: 'https://importia.pages.dev',
    blurb:
      'A scroll-choreographed digital business card for an import brand — built on the cinematic-sites kit and deployed to Cloudflare Pages.',
    stack: ['Cloudflare', 'GSAP', 'Lenis'],
    accentVar: 'var(--accent)',
    posterGlyph: 'IMPORTIA · V',
    posterMotif: 'card',
  },
  {
    id: 'imkarton',
    preview: '/portfolio/imkarton.jpg',
    available: true,
    title: 'Imkarton',
    subtitle: 'Cinematic Visitenkarte',
    label: 'PACKAGING / DE',
    url: 'https://imkarton.pages.dev',
    blurb:
      "A sister Visitenkarte build to Importia — the same cinematic signature applied to a different brand category. Demonstrates the kit's tonal range.",
    stack: ['Cloudflare', 'GSAP', 'Lenis'],
    accentVar: 'var(--accent-2)',
    posterGlyph: 'IMKARTON · PKG',
    posterMotif: 'box',
  },
  {
    id: 'noquito',
    preview: '/portfolio/noquito.jpg',
    available: true,
    title: 'Noquito',
    subtitle: 'Bilingual DE/EN Landing',
    label: 'ANTI-MOSQUITO / B2C',
    url: 'https://noquito.pages.dev',
    blurb:
      'A cheeky, conversion-focused bilingual landing for a residential anti-mosquito screen brand. Demonstrates tonal range across the agency portfolio.',
    stack: ['Cloudflare', 'i18n', 'Stripe'],
    accentVar: 'var(--accent)',
    posterGlyph: 'NOQUITO · DE/EN',
    posterMotif: 'screen',
  },
];

